package com.example.calview.feature.dashboard

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.withStyle
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.calview.core.ui.theme.Inter

/**
 * Privacy Policy screen displaying the app's privacy policy.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PrivacyPolicyScreen(
    onBack: () -> Unit
) {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { 
                    Text(
                        "Privacy Policy",
                        fontFamily = Inter,
                        fontWeight = FontWeight.Bold
                    )
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back"
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.background
                )
            )
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 20.dp, vertical = 16.dp)
        ) {
            // Title
            Text(
                text = "CALVIEW PRIVACY POLICY",
                fontFamily = Inter,
                fontWeight = FontWeight.Bold,
                fontSize = 18.sp,
                color = MaterialTheme.colorScheme.onBackground
            )
            
            Spacer(modifier = Modifier.height(8.dp))
            
            Text(
                text = "Last Updated: December 31, 2024",
                fontFamily = Inter,
                fontSize = 12.sp,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Introduction
            PolicySection(
                content = """This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use CalView and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Definitions Section
            PolicySectionWithTitle(
                title = "Definitions",
                content = """For the purposes of this Privacy Policy:

• Account means a unique account created for You to access our Service or parts of our Service.

• Application refers to CalView, the calorie tracking and nutrition application provided by the Company.

• Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to CalView.

• Country refers to: Kenya

• Device means any device that can access the Service such as a smartphone, computer, or digital tablet.

• Personal Data is any information that relates to an identified or identifiable individual.

• Health Data refers to nutritional information, calorie intake, weight measurements, fitness goals, and other health-related data You input into the Application.

• Service refers to the Application.

• Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.

• You means the individual accessing or using the Service."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Types of Data Collected
            PolicySectionWithTitle(
                title = "Types of Data Collected",
                content = """Personal Data
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
• Email address
• First name and last name
• Profile picture (if provided)
• Usage Data

Health and Nutrition Data
To provide our calorie tracking service, We collect:
• Food logs and meal photos
• Calorie intake and nutritional information
• Macronutrient data (protein, carbohydrates, fats)
• Weight measurements and body composition data
• Fitness goals and preferences
• Water intake tracking

Usage Data
Usage Data is collected automatically when using the Service and may include:
• Your Device's Internet Protocol address (IP address)
• Device type, operating system, and unique device identifiers
• The pages of our Service that You visit
• The time and date of Your visit
• Time spent on those pages
• App usage patterns and feature interactions

Data from Third-Party Services
If You connect Google Health Connect or Apple HealthKit:
• Steps count and walking/running distance
• Exercise and workout data
• Calories burned
• Other fitness metrics You choose to share"""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Use of Data
            PolicySectionWithTitle(
                title = "Use of Your Personal Data",
                content = """The Company may use Personal Data for the following purposes:

• To provide and maintain our Service: Including calorie calculations, nutritional analysis, and personalized recommendations.

• To manage Your Account: To manage Your registration as a user of the Service and provide access to different functionalities.

• To provide AI-powered food scanning: We may process food photos to identify foods and estimate nutritional content.

• To track Your progress: To display Your calorie intake, nutrition goals, and health trends over time.

• To contact You: By email or push notifications regarding updates, security alerts, or informative communications related to the Service.

• To improve our Service: Through data analysis, identifying usage trends, and evaluating the effectiveness of our features.

• For personalized recommendations: To provide customized meal suggestions and nutrition advice based on Your goals."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Health Data Processing
            PolicySectionWithTitle(
                title = "Health Data Processing",
                content = """Your health and nutrition data is handled with special care:

On-Device Processing
• Food photos are processed for AI analysis to identify foods
• Your daily calorie and macro calculations are performed locally
• Personal health metrics are stored securely on Your device

Cloud Synchronization
• If You create an account, Your food logs may be synchronized to our secure servers to enable access across devices
• You may delete Your synchronized data at any time through the app settings

Google Health Connect / Apple HealthKit
• We only access the specific data types You explicitly authorize
• Exercise and step data are used to calculate calories burned
• This data is processed according to Google's and Apple's health data policies
• You can revoke access at any time through Your device settings"""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Data Retention
            PolicySectionWithTitle(
                title = "Retention of Your Personal Data",
                content = """The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.

• Account data is retained while Your account is active
• Health and nutrition logs are retained until You delete them
• Usage Data is generally retained for analytical purposes for up to 24 months
• If You delete Your account, Your Personal Data will be removed within 30 days

You may request deletion of Your data at any time by contacting Us or using the "Delete Account" feature in the app."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Data Transfer
            PolicySectionWithTitle(
                title = "Transfer of Your Personal Data",
                content = """Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.

This means that this information may be transferred to — and maintained on — computers located outside of Your country where data protection laws may differ.

Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.

The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Data Deletion
            PolicySectionWithTitle(
                title = "Delete Your Personal Data",
                content = """You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.

Our Service gives You the ability to delete certain information about You from within the Service:

• Delete individual food logs and meals
• Clear Your weight history
• Delete Your entire account and all associated data

You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.

Please note that We may need to retain certain information when we have a legal obligation or lawful basis to do so."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Disclosure
            PolicySectionWithTitle(
                title = "Disclosure of Your Personal Data",
                content = """Business Transactions
If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data becomes subject to a different Privacy Policy.

Law Enforcement
Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.

We Do NOT:
• Sell Your Personal Data to third parties
• Share Your health data with advertisers
• Use Your data for purposes other than providing and improving the Service"""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Security
            PolicySectionWithTitle(
                title = "Security of Your Personal Data",
                content = """The security of Your Personal Data is important to Us. We implement appropriate technical and organizational measures to protect Your data, including:

• Encryption of data in transit and at rest
• Secure authentication methods
• Regular security assessments

However, remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Children's Privacy
            PolicySectionWithTitle(
                title = "Children's Privacy",
                content = """Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.

If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Changes
            PolicySectionWithTitle(
                title = "Changes to this Privacy Policy",
                content = """We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective.

You are advised to review this Privacy Policy periodically for any changes."""
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Contact
            PolicySectionWithTitle(
                title = "Contact Us",
                content = """If you have any questions about this Privacy Policy, You can contact us:

By email: support@calview.app

By using CalView, You acknowledge that You have read and understood this Privacy Policy and agree to its terms."""
            )
            
            Spacer(modifier = Modifier.height(40.dp))
        }
    }
}

@Composable
private fun PolicySection(content: String) {
    Text(
        text = content,
        fontFamily = Inter,
        fontSize = 14.sp,
        lineHeight = 22.sp,
        color = MaterialTheme.colorScheme.onSurface
    )
}

@Composable
private fun PolicySectionWithTitle(title: String, content: String) {
    Text(
        text = buildAnnotatedString {
            withStyle(SpanStyle(fontWeight = FontWeight.Bold, fontSize = 16.sp)) {
                append(title)
            }
            append("\n\n")
            append(content)
        },
        fontFamily = Inter,
        fontSize = 14.sp,
        lineHeight = 22.sp,
        color = MaterialTheme.colorScheme.onSurface
    )
}
